# Generated by Django 3.2.8 on 2021-10-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(
                decimal_places=2,
                default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='balance',
            field=models.DecimalField(
                decimal_places=2,
                default=0.0, max_digits=10),
        ),
    ]
