# Generated by Django 3.2.8 on 2021-10-12 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_service', '0003_auto_20211012_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_id',
            new_name='transaction_id',
        ),
    ]
